[package]
name = "dsh-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dsh-tools = { path = "../dsh-tools" }
serde_json.workspace = true
async-trait.workspace = true

[dev-dependencies]
dsh-llm = { path = "../dsh-llm" }
tokio = { workspace = true, features = ["rt", "macros"] }